services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    image: backend_service
    container_name: backend_service_container
    runtime: nvidia
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: >
      bash -c "/usr/local/bin/ollama serve & uvicorn main:app --host 0.0.0.0 --port 8000 & wait"


  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    image: frontend_service
    container_name: frontend_service_container
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    command: >
      streamlit run app.py --server.port=8501 --server.address=0.0.0.0
